#!/usr/bin/R

#   ```{r Installation}
# # To install the stable version on CRAN:
install.packages('animation')
# ```

# ```{r To install the GitHub version under development:}
install.packages('animation', repos = 'http://yihui.name/xran')
# ```

# ```{r If you want to contribute, the documentation and NAMESPACE of this package are generated by roxygen2 and Rd2roxygen:}
# if ((!require('Rd2roxygen') install.packages('Rd2roxygen')
#   library(Rd2roxygen)
#   rab('animation', install = TRUE)
#     ```
  
#     ```{r Contact}
#     # Bugs and feature requests can be filed to 
#     # https://github.com/yihui/animation/issues
#     # Pull requests are also welcome.
